pipeline {
        agent none
        stages {
         
          stage("build & SonarQube Analysis") {
            agent any
            steps {
              withSonarQubeEnv('Sonar_Server') {
                sh 'mvn clean package sonar:sonar'
              }
            }
          }
        }
      }
